# Site Configuration
title: "Newgens.lol Blog"
description: "Cybersec FR"
baseurl: "newgens.lol"


theme: minima
google_fonts: "Pixelify+Sans:wght@400..700"
color_scheme: dark
background: "#000000"
text_color: "#ffffff"
accent_color: "#cccccc"


collections:
  posts:
    output: false 
permalink: pretty
excerpt_separator: "<!--more-->"


plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
