# Site Configuration
title: "Newgens.lol Blog"
description: "THOUGHTS IN NEGATIVE SPACE"
url: "https://yourusername.github.io"
baseurl: ""

# Design Settings
theme: minima
google_fonts: "Pixelify+Sans:wght@400..700"
color_scheme: dark
background: "#000000"
text_color: "#ffffff"
accent_color: "#cccccc"

# Content Settings
collections:
  posts:
    output: false  # We'll handle display on index
permalink: pretty
excerpt_separator: "<!--more-->"

# Technical Settings
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
